name: "Feature request"
description: Suggest an idea for this plugin.
labels: [ "enhancement" ]

body:
  - type: textarea
    id: related_problem
    attributes:
      label: "Is your feature request related to a problem?"
      description: "Please describe a clear and concise description of what the problem is."
      value: "No."

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      value: "Not acceptable."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: true
